config/routes.rb
Tasks::Application.routes.draw do
  root :to => "tasks#index"
  resources :tasks
  resources :blog

  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
	validates :task, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
respond_to :html, :xml

  def index
  	@task = Task.new
  	@tasks = Task.all
    respond_with(@tasks)
  end

  def create
  	#render :text => params.inspect
  	Task.create (get_task)
  	redirect_to :back, :notice =>"Your task has been sucessfully created"
  end

  def edit
  	@task = Task.find params[:id]
  end

  def update
  	task = Task.find params[:id]
  	if task.update_attributes (get_task)
  		redirect_to tasks_path, :notice => 'Your task has successfully been updated.'
  	else
  		redirect_to :back, :notice => 'There was an error updating your task.'
  	end
  end

  def destroy
  	Task.destroy params[:id]
  	redirect_to :back, :notice => 'Task has been deleted'
  end

  private
  def get_task
    params.require(:task).permit(:task)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/blog/index.html.erb
<h1>Blog#index</h1>
<p>Find me in app/views/blog/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, message| %>
	<!-- <div id="flash_<%= name %>">
		<%= message %>
	</div> -->
	<%= content_tag :div, message, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
	<%= f.label :task %>
	<%= f.text_field :task%>
	<%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1> Edit </h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<!--<h1>Tasks#index</h1>-->
<h1>Tasks</h1>

<%= render 'form' %>

<u1>
	<% for task in @tasks %>
		<table border = "1" id="task_<%= task.id%>">
			<tr>
			<td width = 300 px><%= task.task%></td>
			<td><%= link_to 'Edit', edit_task_path(task) %></td>
			<td><%= link_to 'Delete', task, :method => 'delete' %></td>
			</tr>
		</table>
	<%end%>
</u1>

<u1>
	<%= link_to 'Blog', blog_index_path, :confirm => 'go to blog?' %>
</u1>